#Settings for tornado physics calculations
[physics]
	#Enable tornado physics
	physicsEnabled = true
	#The tick rate of tornado physics calculations
	# Default: 1
	# Range: 1 ~ 10
	tickSpeed = 1
	#Defines tornado pull range by multiplying default size of Weather2 tornado
	# Default: 0.5
	# Range: 0.1 ~ 100.0
	pullRange = 0.5
	#Offsets tornado center's height down (because by default it's too high)
	# Default: 30.0
	# Range: 0.0 ~ 200.0
	heightOffset = 30.0
	#Defines how much sub-level mass effected by tornado pull
	# Default: 1000.0
	# Range: 0.0 ~ 100000.0
	massResistance = 1000.0
	#Defines the maximum speed tornado can pull
	# Default: 200.0
	# Range: 0.0 ~ 10000.0
	maxSpeed = 200.0
	#Defines the speed of sub-level rotation when pulled by tornado
	# Default: 0.1
	# Range: 0.0 ~ 10000.0
	angularSpeed = 0.1
	#Max angular impulse speed applied to sublevel
	# Default: 50.0
	# Range: 0.0 ~ 10000.0
	angularLimit = 50.0
	#How wide object orbits the tornado
	# Default: 50.0
	# Range: 0.0 ~ 10000.0
	baseOrbit = 50.0
	#Defines the strength of tornado's inward pull
	# Default: 20.0
	# Range: 0.0 ~ 10000.0
	baseInward = 20.0
	#How much the tornado lifts the object
	# Default: 3.5
	# Range: 0.0 ~ 10000.0
	baseLift = 3.5
	#Wind grip strength
	# Default: 0.15
	# Range: 0.0 ~ 1000.0
	windGrip = 0.15

#Settings for block destruction
[destruction]
	#VANILLA - breaks blocks
	#SABLE - turns destroyed blocks into a sub-level
	#Allowed Values: OFF, VANILLA, SABLE
	destructionMode = "VANILLA"
	#Delay between every destruction attempts
	# Default: 10
	# Range: 0 ~ 1000
	destructionDelay = 10
	#List of blocks that can be broken with Tornado (use # for item tags)
	destroyableBlocks = ["#minecraft:leaves", "#minecraft:logs", "minecraft:oak_planks", "#aeronautics:envelope", "#create:windmill_sails"]
	#Amount of block destruction attempts per one destruction tick
	# Default: 1
	# Range: 0 ~ 1000
	destructionAttempts = 1
	#Maximum amount of blocks that will be detached when SABLE mode enabled
	# Default: 5
	# Range: 1 ~ 100
	clusterSize = 5
	#Whether to drop destroyed blocks as items when VANILLA mode enabled
	dropBlocks = false
